apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: WhoIAm
  description: An example of a Backstage application.
  links:
    - url: https://empathy.co
      title: Empathy's website
      icon: web
    - url: https://empathyco.github.io/platform-whoiam/
      title: Who I Am example site
      icon: web
  annotations:
    github.com/project-slug: empathyco/platform-backstage
    # backstage.io/techdocs-ref: url:https://github.com/backstage/backstage
spec:
  type: Website
  owner: platform
  lifecycle: experimental
